[package]
name = "bottles-cli"
description = "The command-line interface for Bottles Next"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository = "https://github.com/bottlesdevs/next-cli/"
homepage = ""
categories = [""]
keywords = [""]
exclude = [""]

[features]
default = ["fvs"]
fvs = ["bottles-core/fvs"]

[dependencies]
bottles-core.workspace = true
clap = { version = "4.5.23", features = ["derive"] }
futures-util.workspace = true
tokio = { workspace = true, features = ["full"] }
url.workspace = true
