[package]
name = "bottles-cli"
version = "0.1.0"
edition.workspace = true

[features]
default = ["fvs"]
fvs = ["bottles-core/fvs"]

[dependencies]
bottles-core.workspace = true
bottles-plugin-host.workspace = true
clap = { version = "4.5.23", features = ["derive"] }
futures-util.workspace = true
tokio = { workspace = true, features = ["full"] }
url.workspace = true
